from puckel/docker-airflow:1.10.9
RUN pip install boto3
RUN mkdir .aws/
RUN touch .aws/config
RUN echo [default] >> .aws/config
RUN echo region = us-east-1 >> .aws/config
RUN echo output = json >> .aws/config